/**
 * インポート先(整形後)ターゲットスキーマ。
 * 内蔵プリセットと、ユーザーがアップロードしたヘッダーからの動的生成の両方を扱う。
 */
import type {
  SchemaCategory,
  SourceDataset,
  TargetField,
  TargetSchema,
} from '../types';

/** カテゴリの表示名と説明(設定・テンプレート選択画面の見出しに使う) */
export const SCHEMA_CATEGORY_LABELS: Record<
  SchemaCategory,
  { title: string; desc: string }
> = {
  crm: {
    title: 'CRM（顧客管理）',
    desc: 'Salesforce / HubSpot / Dynamics 365 などへのリード・取引先取り込み',
  },
  ma: {
    title: 'MA・メール配信',
    desc: '配信リスト、オプトイン状況、流入経路つきのマーケティング向けリスト',
  },
  card: {
    title: '名刺・人脈',
    desc: '展示会や商談で集めた名刺データ（部署・住所・交換日など）',
  },
  recruit: {
    title: '採用・応募者',
    desc: '応募者リスト、選考ステータス、応募経路',
  },
  accounting: {
    title: '会計・経費',
    desc: '請求明細、経費精算（日付・金額・勘定科目・税区分）',
  },
  logistics: {
    title: '配送・EC',
    desc: '送り状データ、受注データ、商品マスタ（住所・電話の表記ゆれ修正が効きます）',
  },
  ads: {
    title: '広告レポート',
    desc: '媒体ごとにバラバラな広告レポートを統一フォーマットへ',
  },
  hr: {
    title: '人事・勤怠',
    desc: '従業員名簿、勤怠・工数データ',
  },
};

/** 設定画面などでカテゴリを列挙するときの順序 */
export const SCHEMA_CATEGORY_ORDER: SchemaCategory[] = [
  'crm',
  'ma',
  'card',
  'recruit',
  'accounting',
  'logistics',
  'ads',
  'hr',
];

/** Salesforce Lead オブジェクトの代表的な項目 */
const SALESFORCE_LEAD: TargetSchema = {
  id: 'salesforce-lead',
  name: 'Salesforce — リード(Lead)',
  origin: 'preset',
  category: 'crm',
  fields: [
    {
      key: 'LastName',
      label: '姓',
      required: true,
      type: 'string',
      maxLength: 80,
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name', 'family name'],
    },
    {
      key: 'FirstName',
      label: '名',
      required: false,
      type: 'string',
      maxLength: 40,
      aliases: ['名', 'firstname', 'first name', 'given name'],
    },
    {
      key: 'Company',
      label: '会社名',
      required: true,
      type: 'string',
      maxLength: 255,
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '団体名',
        'company',
        'account',
        'organization',
        '組織名',
      ],
    },
    {
      key: 'Title',
      label: '役職',
      required: false,
      type: 'string',
      maxLength: 128,
      aliases: ['役職', '肩書', '職位', 'title', 'position', 'job title'],
    },
    {
      key: 'Email',
      label: 'メール',
      required: false,
      type: 'email',
      maxLength: 80,
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'Phone',
      label: '電話番号',
      required: false,
      type: 'phone',
      maxLength: 40,
      aliases: ['電話', '電話番号', 'tel', 'phone', 'telephone', '連絡先'],
    },
    {
      key: 'MobilePhone',
      label: '携帯電話',
      required: false,
      type: 'phone',
      maxLength: 40,
      aliases: ['携帯', '携帯電話', 'mobile', 'cell', 'ケータイ'],
    },
    {
      key: 'Street',
      label: '町名・番地',
      required: false,
      type: 'string',
      maxLength: 255,
      aliases: ['住所', '町名', '番地', 'street', 'address'],
    },
    {
      key: 'City',
      label: '市区町村',
      required: false,
      type: 'string',
      maxLength: 40,
      aliases: ['市区町村', '市', '区', '町村', 'city', '住所2'],
    },
    {
      key: 'State',
      label: '都道府県',
      required: false,
      type: 'string',
      maxLength: 80,
      aliases: ['都道府県', '県', 'state', 'prefecture'],
    },
    {
      key: 'PostalCode',
      label: '郵便番号',
      required: false,
      type: 'string',
      maxLength: 20,
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode', 'post code'],
    },
    {
      key: 'Country',
      label: '国',
      required: false,
      type: 'string',
      maxLength: 80,
      aliases: ['国', '国名', 'country', '国・地域'],
    },
    {
      key: 'Website',
      label: 'Webサイト',
      required: false,
      type: 'url',
      maxLength: 255,
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト', 'hp'],
    },
    {
      key: 'LeadSource',
      label: 'リードソース',
      required: false,
      type: 'string',
      aliases: [
        'リードソース',
        '流入元',
        '獲得経路',
        'source',
        'leadsource',
        '経路',
      ],
      options: [
        'Web',
        '電話問い合わせ',
        '展示会',
        '紹介',
        '外部リスト',
        'パートナー',
        'その他',
      ],
    },
    {
      key: 'Industry',
      label: '業種',
      required: false,
      type: 'string',
      aliases: ['業種', '業界', 'industry'],
      options: [
        '製造',
        '情報通信',
        '建設',
        '金融',
        '小売',
        '医療',
        '教育',
        '公共',
        'その他',
      ],
    },
  ],
};

/**
 * HubSpot コンタクトの代表的な項目。
 * キーは HubSpot の内部プロパティ名(インポートCSVの列見出しに使える)。
 * 新規作成に必須なのは email(一意キー)だけで、姓名は任意。
 */
const HUBSPOT_CONTACT: TargetSchema = {
  id: 'hubspot-contact',
  name: 'HubSpot — コンタクト(Contact)',
  origin: 'preset',
  category: 'crm',
  fields: [
    {
      key: 'email',
      label: 'Email',
      required: true,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'lastname',
      label: '姓(Last name)',
      required: false,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'firstname',
      label: '名(First name)',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name', 'given name'],
    },
    {
      key: 'company',
      label: 'Company name',
      required: false,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        'company',
        'organization',
      ],
    },
    {
      key: 'jobtitle',
      label: 'Job title',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', 'title', 'jobtitle', 'position'],
    },
    {
      key: 'phone',
      label: 'Phone number',
      required: false,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', '連絡先'],
    },
    {
      key: 'mobilephone',
      label: 'Mobile phone number',
      required: false,
      type: 'phone',
      aliases: ['携帯', '携帯電話', 'mobile', 'mobilephone', 'cell'],
    },
    {
      key: 'website',
      label: 'Website URL',
      required: false,
      type: 'url',
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト'],
    },
    {
      key: 'address',
      label: 'Street address',
      required: false,
      type: 'string',
      aliases: ['住所', '町名', '番地', 'address', 'street'],
    },
    {
      key: 'city',
      label: 'City',
      required: false,
      type: 'string',
      aliases: ['市区町村', '市', 'city', '住所2'],
    },
    {
      key: 'state',
      label: 'State/Region',
      required: false,
      type: 'string',
      aliases: ['都道府県', '県', 'state', 'prefecture', 'region'],
    },
    {
      key: 'zip',
      label: 'Postal code',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode'],
    },
    {
      key: 'country',
      label: 'Country/Region',
      required: false,
      type: 'string',
      aliases: ['国', '国名', 'country', '国・地域'],
    },
    {
      key: 'industry',
      label: 'Industry',
      required: false,
      type: 'string',
      aliases: ['業種', '業界', 'industry'],
    },
    {
      key: 'lifecyclestage',
      label: 'Lifecycle stage',
      required: false,
      type: 'string',
      aliases: [
        'ライフサイクル',
        'ライフサイクルステージ',
        'lifecycle',
        'lifecycle stage',
        'ステージ',
      ],
      options: [
        'subscriber',
        'lead',
        'marketingqualifiedlead',
        'salesqualifiedlead',
        'opportunity',
        'customer',
        'evangelist',
        'other',
      ],
      optionLabels: {
        subscriber: 'Subscriber(購読者)',
        lead: 'Lead(リード)',
        marketingqualifiedlead: 'MQL',
        salesqualifiedlead: 'SQL',
        opportunity: 'Opportunity(商談)',
        customer: 'Customer(顧客)',
        evangelist: 'Evangelist',
        other: 'Other',
      },
    },
    {
      key: 'hs_lead_status',
      label: 'Lead status',
      required: false,
      type: 'string',
      aliases: ['ステータス', 'status', 'lead status', '状態'],
      options: [
        'NEW',
        'OPEN',
        'IN_PROGRESS',
        'OPEN_DEAL',
        'UNQUALIFIED',
        'CONNECTED',
      ],
      optionLabels: {
        NEW: 'New(新規)',
        OPEN: 'Open(対応中)',
        IN_PROGRESS: 'In progress(進行中)',
        OPEN_DEAL: 'Open deal(商談化)',
        UNQUALIFIED: 'Unqualified(対象外)',
        CONNECTED: 'Connected(接触済み)',
      },
    },
  ],
};

/**
 * Microsoft Dynamics 365 Sales のリード(Lead)。
 * キーは Dataverse の論理名(データインポート時の列名に使われる)。
 */
const DYNAMICS_LEAD: TargetSchema = {
  id: 'dynamics-lead',
  name: 'Microsoft Dynamics 365 — リード(Lead)',
  origin: 'preset',
  category: 'crm',
  fields: [
    {
      key: 'subject',
      label: 'トピック',
      required: true,
      type: 'string',
      aliases: ['トピック', '件名', '要件', 'topic', 'subject', 'タイトル'],
    },
    {
      key: 'lastname',
      label: '姓',
      required: true,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'firstname',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'companyname',
      label: '会社名',
      required: false,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '団体名',
        '組織名',
        'company',
        'companyname',
        'account',
      ],
    },
    {
      key: 'jobtitle',
      label: '役職',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', '職位', 'title', 'jobtitle', 'position'],
    },
    {
      key: 'emailaddress1',
      label: 'メール',
      required: false,
      type: 'email',
      aliases: [
        'メール',
        'メールアドレス',
        'email',
        'e-mail',
        'mail',
        'emailaddress',
      ],
    },
    {
      key: 'telephone1',
      label: '勤務先電話',
      required: false,
      type: 'phone',
      aliases: [
        '電話',
        '電話番号',
        'tel',
        'phone',
        '連絡先',
        'business phone',
        'telephone',
      ],
    },
    {
      key: 'mobilephone',
      label: '携帯電話',
      required: false,
      type: 'phone',
      aliases: ['携帯', '携帯電話', 'mobile', 'cell', 'ケータイ'],
    },
    {
      key: 'address1_line1',
      label: '住所(番地)',
      required: false,
      type: 'string',
      aliases: ['住所', '町名', '番地', 'street', 'address', 'address1'],
    },
    {
      key: 'address1_city',
      label: '市区町村',
      required: false,
      type: 'string',
      aliases: ['市区町村', '市', '区', 'city'],
    },
    {
      key: 'address1_stateorprovince',
      label: '都道府県',
      required: false,
      type: 'string',
      aliases: ['都道府県', '県', 'state', 'prefecture', 'province'],
    },
    {
      key: 'address1_postalcode',
      label: '郵便番号',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode', 'post code'],
    },
    {
      key: 'websiteurl',
      label: 'Webサイト',
      required: false,
      type: 'url',
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト', 'hp'],
    },
    {
      key: 'leadsourcecode',
      label: 'リードソース',
      required: false,
      type: 'string',
      aliases: [
        'リードソース',
        '流入元',
        '獲得経路',
        'source',
        'leadsource',
        '経路',
      ],
    },
    {
      key: 'industrycode',
      label: '業種',
      required: false,
      type: 'string',
      aliases: ['業種', '業界', 'industry'],
    },
    {
      key: 'description',
      label: '説明(備考)',
      required: false,
      type: 'string',
      aliases: [
        '備考',
        'メモ',
        '説明',
        'コメント',
        'notes',
        'description',
        'remarks',
        '摘要',
      ],
    },
  ],
};

/** Microsoft Dynamics 365 Sales の取引先担当者(Contact)。 */
const DYNAMICS_CONTACT: TargetSchema = {
  id: 'dynamics-contact',
  name: 'Microsoft Dynamics 365 — 取引先担当者(Contact)',
  origin: 'preset',
  category: 'crm',
  fields: [
    {
      key: 'lastname',
      label: '姓',
      required: true,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'firstname',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'parentcustomerid',
      label: '会社名(取引先)',
      required: false,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '取引先',
        'company',
        'account',
        '組織名',
      ],
    },
    {
      key: 'jobtitle',
      label: '役職',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', '職位', 'title', 'jobtitle', 'position'],
    },
    {
      key: 'emailaddress1',
      label: 'メール',
      required: false,
      type: 'email',
      aliases: [
        'メール',
        'メールアドレス',
        'email',
        'e-mail',
        'mail',
        'emailaddress',
      ],
    },
    {
      key: 'telephone1',
      label: '勤務先電話',
      required: false,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', '連絡先', 'telephone'],
    },
    {
      key: 'mobilephone',
      label: '携帯電話',
      required: false,
      type: 'phone',
      aliases: ['携帯', '携帯電話', 'mobile', 'cell', 'ケータイ'],
    },
    {
      key: 'address1_stateorprovince',
      label: '都道府県',
      required: false,
      type: 'string',
      aliases: ['都道府県', '県', 'state', 'prefecture', 'province'],
    },
    {
      key: 'address1_line1',
      label: '住所(番地)',
      required: false,
      type: 'string',
      aliases: ['住所', '町名', '番地', 'street', 'address', 'address1'],
    },
    {
      key: 'address1_postalcode',
      label: '郵便番号',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode'],
    },
    {
      key: 'websiteurl',
      label: 'Webサイト',
      required: false,
      type: 'url',
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト'],
    },
    {
      key: 'description',
      label: '説明(備考)',
      required: false,
      type: 'string',
      aliases: [
        '備考',
        'メモ',
        '説明',
        'コメント',
        'notes',
        'description',
        'remarks',
        '摘要',
      ],
    },
  ],
};

/** Microsoft Dynamics 365 Sales の取引先企業(Account)。 */
const DYNAMICS_ACCOUNT: TargetSchema = {
  id: 'dynamics-account',
  name: 'Microsoft Dynamics 365 — 取引先企業(Account)',
  origin: 'preset',
  category: 'crm',
  fields: [
    {
      key: 'name',
      label: '取引先名',
      required: true,
      type: 'string',
      aliases: [
        '取引先名',
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '団体名',
        '組織名',
        'company',
        'account',
        'name',
      ],
    },
    {
      key: 'telephone1',
      label: '主要電話',
      required: false,
      type: 'phone',
      aliases: [
        '電話',
        '電話番号',
        'tel',
        'phone',
        '代表電話',
        'main phone',
        'telephone',
      ],
    },
    {
      key: 'websiteurl',
      label: 'Webサイト',
      required: false,
      type: 'url',
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト', 'hp'],
    },
    {
      key: 'address1_stateorprovince',
      label: '都道府県',
      required: false,
      type: 'string',
      aliases: ['都道府県', '県', 'state', 'prefecture', 'province'],
    },
    {
      key: 'address1_city',
      label: '市区町村',
      required: false,
      type: 'string',
      aliases: ['市区町村', '市', '区', 'city'],
    },
    {
      key: 'address1_line1',
      label: '住所(番地)',
      required: false,
      type: 'string',
      aliases: ['住所', '町名', '番地', 'street', 'address', 'address1'],
    },
    {
      key: 'address1_postalcode',
      label: '郵便番号',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode'],
    },
    {
      key: 'industrycode',
      label: '業種',
      required: false,
      type: 'string',
      aliases: ['業種', '業界', 'industry'],
    },
    {
      key: 'numberofemployees',
      label: '従業員数',
      required: false,
      type: 'number',
      aliases: [
        '従業員数',
        '社員数',
        '人数',
        'employees',
        'number of employees',
      ],
    },
    {
      key: 'revenue',
      label: '年間売上',
      required: false,
      type: 'number',
      aliases: ['売上', '年商', '年間売上', 'revenue', 'annual revenue'],
    },
    {
      key: 'description',
      label: '説明(備考)',
      required: false,
      type: 'string',
      aliases: [
        '備考',
        'メモ',
        '説明',
        'コメント',
        'notes',
        'description',
        'remarks',
        '摘要',
      ],
    },
  ],
};

// ── MA・メール配信 ──────────────────────────────────────────

/** MA/メール配信ツール向けの配信リスト(オプトイン・流入経路つき) */
const MA_CONTACT_LIST: TargetSchema = {
  id: 'ma-contact-list',
  name: 'MA — 配信リスト',
  origin: 'preset',
  category: 'ma',
  fields: [
    {
      key: 'Email',
      label: 'メールアドレス',
      required: true,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'LastName',
      label: '姓',
      required: false,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'FirstName',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'Company',
      label: '会社名',
      required: false,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        'company',
        'organization',
      ],
    },
    {
      key: 'OptInStatus',
      label: '配信同意',
      required: false,
      type: 'string',
      aliases: [
        '配信同意',
        'オプトイン',
        '同意',
        'opt-in',
        'optin',
        'subscribed',
        'consent',
      ],
      options: ['subscribed', 'unsubscribed', 'pending'],
      optionLabels: {
        subscribed: '配信可',
        unsubscribed: '配信停止',
        pending: '未確認',
      },
      defaultValue: 'pending',
    },
    {
      key: 'Source',
      label: '流入経路',
      required: false,
      type: 'string',
      aliases: [
        '流入経路',
        '経路',
        '獲得経路',
        'ソース',
        'source',
        'utm_source',
        '媒体',
      ],
    },
    {
      key: 'ListName',
      label: 'リスト名・タグ',
      required: false,
      type: 'string',
      aliases: [
        'リスト',
        'リスト名',
        'タグ',
        'セグメント',
        'list',
        'tag',
        'segment',
      ],
    },
    {
      key: 'LeadScore',
      label: 'リードスコア',
      required: false,
      type: 'number',
      aliases: ['スコア', 'リードスコア', 'score', 'lead score', '点数'],
    },
  ],
};

/**
 * Adobe Marketo Engage のリスト取り込み(Import a List of People)用。
 *
 * キーは Marketo の REST API 名。リスト取り込みでは CSV の1行目に
 * REST API 名を並べると、そのまま人物フィールドへ割り当てられる。
 * 必須は email のみで、これが重複判定(dedupe)のキーになる。
 * 参考: Adobe Experience League「Import a List of People」/
 *       「List of Standard Fields」
 *
 * 注意:
 *  - leadStatus の選択肢は購読(インスタンス)ごとに異なるため、
 *    ここでは候補を固定せず自由入力にしている。
 *  - unsubscribed には既定値を入れていない。未割当のまま取り込むと
 *    既存の配信停止(オプトアウト)を一括で上書きしてしまうため、
 *    意図して列を割り当てたときだけ値が入るようにしている。
 */
const MARKETO_LEAD: TargetSchema = {
  id: 'marketo-lead',
  name: 'Marketo Engage — 人物リスト取り込み',
  origin: 'preset',
  category: 'ma',
  fields: [
    {
      key: 'email',
      label: 'メールアドレス(Email Address)',
      required: true,
      type: 'email',
      aliases: [
        'メール',
        'メールアドレス',
        'email',
        'e-mail',
        'mail',
        'email address',
      ],
    },
    {
      key: 'lastName',
      label: '姓(Last Name)',
      required: false,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name', 'family name'],
    },
    {
      key: 'firstName',
      label: '名(First Name)',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name', 'given name'],
    },
    {
      key: 'company',
      label: '会社名(Company Name)',
      required: false,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '団体名',
        'company',
        'organization',
        '組織名',
      ],
    },
    {
      key: 'title',
      label: '役職(Job Title)',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', '職位', 'title', 'job title', 'position'],
    },
    {
      key: 'department',
      label: '部署(Department)',
      required: false,
      type: 'string',
      aliases: ['部署', '部門', '所属', 'department', 'division'],
    },
    {
      key: 'phone',
      label: '電話番号(Phone Number)',
      required: false,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', 'telephone', '連絡先'],
    },
    {
      key: 'mobilePhone',
      label: '携帯電話(Mobile Phone Number)',
      required: false,
      type: 'phone',
      aliases: [
        '携帯',
        '携帯電話',
        'mobile',
        'mobilephone',
        'cell',
        'ケータイ',
      ],
    },
    {
      key: 'address',
      label: '住所(Address)',
      required: false,
      type: 'string',
      aliases: ['住所', '町名', '番地', '建物名', 'address', 'street'],
    },
    {
      key: 'city',
      label: '市区町村(City)',
      required: false,
      type: 'string',
      aliases: ['市区町村', '市', '区', '町村', 'city', '住所2'],
    },
    {
      key: 'state',
      label: '都道府県(State)',
      required: false,
      type: 'string',
      aliases: ['都道府県', '県', 'state', 'prefecture', 'region'],
    },
    {
      key: 'postalCode',
      label: '郵便番号(Postal Code)',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postalcode', 'post code'],
    },
    {
      key: 'country',
      label: '国(Country)',
      required: false,
      type: 'string',
      aliases: ['国', '国名', 'country', '国・地域'],
    },
    {
      key: 'website',
      label: 'Webサイト(Website)',
      required: false,
      type: 'url',
      aliases: ['url', 'website', 'web', 'ホームページ', 'サイト', 'hp'],
    },
    {
      key: 'industry',
      label: '業種(Industry)',
      required: false,
      type: 'string',
      aliases: ['業種', '業界', 'industry'],
    },
    {
      key: 'numberOfEmployees',
      label: '従業員数(Number of Employees)',
      required: false,
      type: 'number',
      aliases: ['従業員数', '社員数', '人数', '規模', 'employees', 'headcount'],
    },
    {
      key: 'annualRevenue',
      label: '年間売上(Annual Revenue)',
      required: false,
      type: 'number',
      aliases: ['売上', '年商', '年間売上', 'revenue', 'annual revenue'],
    },
    {
      key: 'leadSource',
      label: 'リードソース(Lead Source)',
      required: false,
      type: 'string',
      aliases: [
        'リードソース',
        '流入元',
        '流入経路',
        '獲得経路',
        '経路',
        'source',
        'leadsource',
        'utm_source',
      ],
    },
    {
      key: 'leadStatus',
      label: 'リードステータス(Lead Status)',
      required: false,
      type: 'string',
      aliases: [
        'ステータス',
        'リードステータス',
        '状態',
        'status',
        'lead status',
      ],
    },
    {
      key: 'leadScore',
      label: 'リードスコア(Lead Score)',
      required: false,
      type: 'number',
      aliases: ['スコア', 'リードスコア', 'score', 'lead score', '点数'],
    },
    {
      key: 'unsubscribed',
      label: '配信停止(Unsubscribed)',
      required: false,
      type: 'boolean',
      aliases: [
        '配信停止',
        '停止',
        '解除',
        'unsubscribe',
        'unsubscribed',
        'opt-out',
        'optout',
      ],
      options: ['false', 'true'],
      optionLabels: { false: '配信する', true: '配信しない' },
    },
    {
      key: 'unsubscribedReason',
      label: '配信停止の理由(Unsubscribed Reason)',
      required: false,
      type: 'string',
      aliases: [
        '配信停止理由',
        '停止理由',
        '解除理由',
        'unsubscribed reason',
        'opt-out reason',
      ],
    },
    {
      key: 'mktoPersonNotes',
      label: 'メモ(Person Notes)',
      required: false,
      type: 'string',
      aliases: ['メモ', '備考', 'ノート', 'note', 'notes', 'remarks'],
    },
  ],
};

/** 最小構成のメルマガ配信リスト(とにかく送れればよい用) */
const NEWSLETTER_LIST: TargetSchema = {
  id: 'newsletter-list',
  name: 'メルマガ — 配信リスト（最小構成）',
  origin: 'preset',
  category: 'ma',
  fields: [
    {
      key: 'email',
      label: 'メールアドレス',
      required: true,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'name',
      label: '氏名',
      required: false,
      type: 'string',
      aliases: ['氏名', '名前', 'お名前', 'name', 'full name'],
    },
    {
      key: 'unsubscribed',
      label: '配信停止',
      required: false,
      type: 'boolean',
      aliases: [
        '配信停止',
        '停止',
        '解除',
        'unsubscribe',
        'unsubscribed',
        'opt-out',
      ],
      options: ['false', 'true'],
      optionLabels: { false: '配信する', true: '配信しない' },
      defaultValue: 'false',
    },
    {
      key: 'tags',
      label: 'タグ',
      required: false,
      type: 'string',
      aliases: ['タグ', '分類', 'ラベル', 'tag', 'tags', 'label'],
    },
  ],
};

// ── 名刺・人脈 ──────────────────────────────────────────────

/** 展示会や商談で集めた名刺データ(CRM Lead に無い部署・住所・交換日を持つ) */
const BUSINESS_CARD: TargetSchema = {
  id: 'business-card',
  name: '名刺データ',
  origin: 'preset',
  category: 'card',
  fields: [
    {
      key: 'LastName',
      label: '姓',
      required: true,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'FirstName',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'NameKana',
      label: 'フリガナ',
      required: false,
      type: 'string',
      aliases: [
        'フリガナ',
        'ふりがな',
        'カナ',
        'かな',
        'kana',
        'furigana',
        '読み',
      ],
    },
    {
      key: 'Company',
      label: '会社名',
      required: true,
      type: 'string',
      aliases: [
        '会社名',
        '会社',
        '企業名',
        '法人名',
        '団体名',
        'company',
        'organization',
      ],
    },
    {
      key: 'Department',
      label: '部署',
      required: false,
      type: 'string',
      aliases: [
        '部署',
        '部門',
        '所属',
        '事業部',
        'department',
        'division',
        'section',
      ],
    },
    {
      key: 'Title',
      label: '役職',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', '職位', 'title', 'position', 'job title'],
    },
    {
      key: 'Email',
      label: 'メール',
      required: false,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'Phone',
      label: '電話番号',
      required: false,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', '連絡先', 'ｔｅｌ'],
    },
    {
      key: 'MobilePhone',
      label: '携帯番号',
      required: false,
      type: 'phone',
      aliases: ['携帯', '携帯番号', '携帯電話', 'mobile', 'cell', 'ケータイ'],
    },
    {
      key: 'PostalCode',
      label: '郵便番号',
      required: false,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postal code', 'zipcode'],
    },
    {
      key: 'Address',
      label: '住所',
      required: false,
      type: 'string',
      aliases: ['住所', '所在地', '本社所在地', 'address', '番地'],
    },
    {
      key: 'ExchangedAt',
      label: '名刺交換日',
      required: false,
      type: 'date',
      aliases: [
        '交換日',
        '名刺交換日',
        '取得日',
        '獲得日',
        '日付',
        'date',
        'exchanged',
      ],
    },
    {
      key: 'OwnerName',
      label: '交換した担当者',
      required: false,
      type: 'string',
      aliases: ['担当', '担当者', '自社担当', 'owner', '営業担当'],
    },
    {
      key: 'EventName',
      label: '獲得イベント',
      required: false,
      type: 'string',
      aliases: ['イベント', '展示会', 'セミナー', '獲得経路', 'event', '経路'],
    },
  ],
};

// ── 採用・応募者 ────────────────────────────────────────────

/** ATS(採用管理)向けの応募者リスト */
const APPLICANT_LIST: TargetSchema = {
  id: 'applicant-list',
  name: '採用 — 応募者リスト',
  origin: 'preset',
  category: 'recruit',
  fields: [
    {
      key: 'LastName',
      label: '姓',
      required: true,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'FirstName',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'Email',
      label: 'メール',
      required: true,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'Phone',
      label: '電話番号',
      required: false,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', '連絡先'],
    },
    {
      key: 'Position',
      label: '応募ポジション',
      required: false,
      type: 'string',
      aliases: [
        'ポジション',
        '応募職種',
        '職種',
        '募集職種',
        'position',
        'job',
        '求人',
      ],
    },
    {
      key: 'Stage',
      label: '選考ステータス',
      required: false,
      type: 'string',
      aliases: [
        'ステータス',
        '選考状況',
        '進捗',
        'stage',
        'status',
        '選考ステータス',
      ],
      options: [
        'applied',
        'screening',
        'interview',
        'offer',
        'hired',
        'rejected',
      ],
      optionLabels: {
        applied: '応募',
        screening: '書類選考',
        interview: '面接',
        offer: '内定',
        hired: '入社',
        rejected: '不採用',
      },
      defaultValue: 'applied',
    },
    {
      key: 'Channel',
      label: '応募経路',
      required: false,
      type: 'string',
      aliases: [
        '応募経路',
        '媒体',
        '経路',
        'チャネル',
        'channel',
        'source',
        '流入元',
      ],
    },
    {
      key: 'AppliedAt',
      label: '応募日',
      required: false,
      type: 'date',
      aliases: ['応募日', '登録日', '日付', 'date', 'applied', 'applied at'],
    },
    {
      key: 'Note',
      label: '備考',
      required: false,
      type: 'string',
      aliases: ['備考', 'メモ', 'コメント', 'note', 'notes', 'remarks'],
    },
  ],
};

// ── 会計・経費 ──────────────────────────────────────────────

/** 請求書明細(会計ソフト取り込み向け) */
const INVOICE_LINE: TargetSchema = {
  id: 'invoice-line',
  name: '会計 — 請求明細',
  origin: 'preset',
  category: 'accounting',
  fields: [
    {
      key: 'IssueDate',
      label: '発生日',
      required: true,
      type: 'date',
      aliases: ['日付', '発生日', '取引日', '請求日', 'date', '計上日'],
    },
    {
      key: 'PartnerName',
      label: '取引先',
      required: true,
      type: 'string',
      aliases: [
        '取引先',
        '取引先名',
        '得意先',
        '請求先',
        '支払先',
        'partner',
        '会社名',
      ],
    },
    {
      key: 'RegistrationNumber',
      label: 'インボイス登録番号',
      required: false,
      type: 'string',
      aliases: [
        'インボイス登録番号',
        '登録番号',
        '適格請求書発行事業者登録番号',
        '事業者登録番号',
        'invoice registration number',
        'T番号',
      ],
    },
    {
      key: 'Description',
      label: '摘要',
      required: false,
      type: 'string',
      aliases: ['摘要', '品目', '内容', '明細', '備考', 'description', 'item'],
    },
    {
      key: 'Amount',
      label: '金額(税抜)',
      required: true,
      type: 'number',
      aliases: ['金額', '価格', '合計', '税抜金額', 'amount', 'price', 'total'],
    },
    {
      key: 'TaxRate',
      label: '税区分',
      required: false,
      type: 'string',
      aliases: ['税区分', '消費税', '税率', 'tax', 'tax rate', '税'],
      options: ['10', '8', '0'],
      optionLabels: { '10': '10%', '8': '8%(軽減)', '0': '非課税・対象外' },
      defaultValue: '10',
    },
    {
      key: 'TaxAmount',
      label: '消費税額',
      required: false,
      type: 'number',
      aliases: ['消費税額', '消費税', '税額', 'tax amount', 'vat'],
    },
    {
      key: 'AccountItem',
      label: '勘定科目',
      required: false,
      type: 'string',
      aliases: ['勘定科目', '科目', '費目', 'account', 'account item'],
    },
    {
      key: 'InvoiceNumber',
      label: '請求書番号',
      required: false,
      type: 'string',
      aliases: [
        '請求書番号',
        '伝票番号',
        '番号',
        'invoice',
        'invoice no',
        '請求番号',
      ],
    },
  ],
};

/** 経費精算データ */
const EXPENSE_REPORT: TargetSchema = {
  id: 'expense-report',
  name: '経費精算',
  origin: 'preset',
  category: 'accounting',
  fields: [
    {
      key: 'UsedAt',
      label: '利用日',
      required: true,
      type: 'date',
      aliases: ['利用日', '日付', '使用日', '支払日', 'date', '発生日'],
    },
    {
      key: 'EmployeeName',
      label: '申請者',
      required: true,
      type: 'string',
      aliases: ['申請者', '氏名', '名前', '社員', '担当者', 'employee', 'name'],
    },
    {
      key: 'PayeeName',
      label: '支払先',
      required: false,
      type: 'string',
      aliases: [
        '支払先',
        '店名',
        '利用先',
        '取引先',
        'payee',
        'vendor',
        '店舗',
      ],
    },
    {
      key: 'AccountItem',
      label: '勘定科目',
      required: false,
      type: 'string',
      aliases: ['勘定科目', '科目', '費目', '経費区分', 'account', 'category'],
    },
    {
      key: 'Amount',
      label: '金額',
      required: true,
      type: 'number',
      aliases: ['金額', '合計', '費用', 'amount', 'price', 'total'],
    },
    {
      key: 'TaxRate',
      label: '税区分',
      required: false,
      type: 'string',
      aliases: ['税区分', '消費税', '税率', 'tax', 'tax rate'],
      options: ['10', '8', '0'],
      optionLabels: { '10': '10%', '8': '8%(軽減)', '0': '非課税・対象外' },
      defaultValue: '10',
    },
    {
      key: 'Note',
      label: '摘要',
      required: false,
      type: 'string',
      aliases: ['摘要', '内容', '目的', '備考', 'メモ', 'note', 'description'],
    },
  ],
};

// ── 配送・EC ────────────────────────────────────────────────

/**
 * 配送の送り状データ。
 * 送り状CSVはフォーマットが厳格で、住所・電話・郵便番号の表記ゆれ修正が要る。
 * このアプリの正規化(全角半角・電話番号)が最も効く用途。
 */
const SHIPPING_LABEL: TargetSchema = {
  id: 'shipping-label',
  name: '配送 — 送り状データ',
  origin: 'preset',
  category: 'logistics',
  fields: [
    {
      key: 'RecipientName',
      label: 'お届け先氏名',
      required: true,
      type: 'string',
      aliases: [
        'お届け先',
        '氏名',
        '名前',
        '宛名',
        '送り先',
        'name',
        'recipient',
      ],
    },
    {
      key: 'RecipientKana',
      label: 'お届け先フリガナ',
      required: false,
      type: 'string',
      aliases: ['フリガナ', 'ふりがな', 'カナ', 'kana', '宛名カナ'],
    },
    {
      key: 'PostalCode',
      label: '郵便番号',
      required: true,
      type: 'string',
      aliases: ['郵便番号', '〒', 'zip', 'postal', 'postal code', 'zipcode'],
    },
    {
      key: 'Address1',
      label: '住所1（都道府県・市区町村）',
      required: true,
      type: 'string',
      aliases: ['住所', '住所1', '都道府県', '市区町村', 'address', 'address1'],
    },
    {
      key: 'Address2',
      label: '住所2（番地・建物名）',
      required: false,
      type: 'string',
      aliases: [
        '住所2',
        '番地',
        '建物',
        'マンション',
        'ビル',
        'address2',
        '建物名',
      ],
    },
    {
      key: 'Phone',
      label: '電話番号',
      required: true,
      type: 'phone',
      aliases: ['電話', '電話番号', 'tel', 'phone', '連絡先'],
    },
    {
      key: 'ItemName',
      label: '品名',
      required: false,
      type: 'string',
      aliases: ['品名', '商品名', '内容品', '品目', 'item', 'product', '商品'],
    },
    {
      key: 'Quantity',
      label: '個数',
      required: false,
      type: 'number',
      aliases: ['個数', '数量', '点数', 'quantity', 'qty', '数'],
      defaultValue: '1',
    },
    {
      key: 'DeliveryDate',
      label: '配達希望日',
      required: false,
      type: 'date',
      aliases: [
        '配達希望日',
        '希望日',
        'お届け日',
        '配送日',
        'delivery',
        'date',
      ],
    },
    {
      key: 'DeliveryTime',
      label: '配達希望時間帯',
      required: false,
      type: 'string',
      aliases: ['時間帯', '希望時間', '配達時間', 'time', 'delivery time'],
    },
  ],
};

/** EC の受注データ */
const EC_ORDER: TargetSchema = {
  id: 'ec-order',
  name: 'EC — 受注データ',
  origin: 'preset',
  category: 'logistics',
  fields: [
    {
      key: 'OrderNumber',
      label: '注文番号',
      required: true,
      type: 'string',
      aliases: [
        '注文番号',
        '受注番号',
        '伝票番号',
        'order',
        'order id',
        'order no',
      ],
    },
    {
      key: 'OrderedAt',
      label: '注文日',
      required: false,
      type: 'date',
      aliases: ['注文日', '受注日', '日付', 'date', 'ordered', 'order date'],
    },
    {
      key: 'CustomerName',
      label: '購入者氏名',
      required: true,
      type: 'string',
      aliases: [
        '購入者',
        '注文者',
        '氏名',
        '名前',
        'customer',
        'name',
        'お客様',
      ],
    },
    {
      key: 'Email',
      label: 'メール',
      required: false,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', 'e-mail', 'mail'],
    },
    {
      key: 'ProductCode',
      label: '商品コード',
      required: false,
      type: 'string',
      aliases: [
        '商品コード',
        'sku',
        'jan',
        '品番',
        'product code',
        'item code',
      ],
    },
    {
      key: 'ProductName',
      label: '商品名',
      required: false,
      type: 'string',
      aliases: ['商品名', '品名', '商品', 'product', 'item', 'item name'],
    },
    {
      key: 'Quantity',
      label: '数量',
      required: false,
      type: 'number',
      aliases: ['数量', '個数', '点数', 'quantity', 'qty'],
    },
    {
      key: 'Amount',
      label: '金額',
      required: false,
      type: 'number',
      aliases: ['金額', '合計', 'price', 'amount', 'total', '小計'],
    },
    {
      key: 'ShippingAddress',
      label: '配送先住所',
      required: false,
      type: 'string',
      aliases: [
        '配送先',
        'お届け先住所',
        '住所',
        'address',
        'shipping address',
      ],
    },
  ],
};

/** EC 出品などで使う商品マスタ */
const PRODUCT_MASTER: TargetSchema = {
  id: 'product-master',
  name: 'EC — 商品マスタ',
  origin: 'preset',
  category: 'logistics',
  fields: [
    {
      key: 'Sku',
      label: '商品コード(SKU)',
      required: true,
      type: 'string',
      aliases: [
        '商品コード',
        'sku',
        '品番',
        '型番',
        'product code',
        'item code',
      ],
    },
    {
      key: 'ProductName',
      label: '商品名',
      required: true,
      type: 'string',
      aliases: ['商品名', '品名', '商品', 'product', 'item', 'name'],
    },
    {
      key: 'JanCode',
      label: 'JANコード',
      required: false,
      type: 'string',
      aliases: ['jan', 'janコード', 'ean', 'バーコード', 'jan code'],
    },
    {
      key: 'Category',
      label: 'カテゴリ',
      required: false,
      type: 'string',
      aliases: ['カテゴリ', '分類', 'ジャンル', 'category', 'genre'],
    },
    {
      key: 'Price',
      label: '販売価格',
      required: false,
      type: 'number',
      aliases: ['価格', '販売価格', '税込価格', '定価', 'price', 'amount'],
    },
    {
      key: 'Stock',
      label: '在庫数',
      required: false,
      type: 'number',
      aliases: ['在庫', '在庫数', '数量', 'stock', 'inventory', 'qty'],
    },
    {
      key: 'Description',
      label: '商品説明',
      required: false,
      type: 'string',
      inputKind: 'textarea',
      aliases: ['説明', '商品説明', '詳細', 'description', '備考'],
    },
  ],
};

// ── 広告レポート ────────────────────────────────────────────

/** 媒体ごとにバラバラな広告レポートを統一するフォーマット */
const AD_REPORT: TargetSchema = {
  id: 'ad-report',
  name: '広告 — レポート統合',
  origin: 'preset',
  category: 'ads',
  fields: [
    {
      key: 'Date',
      label: '日付',
      required: true,
      type: 'date',
      aliases: ['日付', '日', '配信日', 'date', 'day', '期間'],
    },
    {
      key: 'Platform',
      label: '媒体',
      required: false,
      type: 'string',
      aliases: [
        '媒体',
        'プラットフォーム',
        '広告media',
        'platform',
        'media',
        'source',
      ],
    },
    {
      key: 'CampaignName',
      label: 'キャンペーン名',
      required: false,
      type: 'string',
      aliases: ['キャンペーン', 'キャンペーン名', 'campaign', 'campaign name'],
    },
    {
      key: 'Impressions',
      label: 'インプレッション',
      required: false,
      type: 'number',
      aliases: [
        'imp',
        'impression',
        'impressions',
        '表示回数',
        'インプレッション',
      ],
    },
    {
      key: 'Clicks',
      label: 'クリック数',
      required: false,
      type: 'number',
      aliases: ['クリック', 'クリック数', 'click', 'clicks'],
    },
    {
      key: 'Cost',
      label: '費用',
      required: false,
      type: 'number',
      aliases: [
        '費用',
        'コスト',
        '広告費',
        '消化金額',
        'cost',
        'spend',
        'amount',
      ],
    },
    {
      key: 'Conversions',
      label: 'コンバージョン',
      required: false,
      type: 'number',
      aliases: ['cv', 'コンバージョン', '成果', 'conversion', 'conversions'],
    },
  ],
};

// ── 人事・勤怠 ──────────────────────────────────────────────

/** 従業員名簿(人事システム取り込み向け) */
const EMPLOYEE_ROSTER: TargetSchema = {
  id: 'employee-roster',
  name: '人事 — 従業員名簿',
  origin: 'preset',
  category: 'hr',
  fields: [
    {
      key: 'EmployeeCode',
      label: '社員番号',
      required: true,
      type: 'string',
      aliases: [
        '社員番号',
        '従業員番号',
        '社員コード',
        'id',
        'employee code',
        '番号',
      ],
    },
    {
      key: 'LastName',
      label: '姓',
      required: true,
      type: 'string',
      aliases: ['姓', '苗字', '名字', 'lastname', 'last name'],
    },
    {
      key: 'FirstName',
      label: '名',
      required: false,
      type: 'string',
      aliases: ['名', 'firstname', 'first name'],
    },
    {
      key: 'NameKana',
      label: 'フリガナ',
      required: false,
      type: 'string',
      aliases: ['フリガナ', 'ふりがな', 'カナ', 'kana', 'furigana'],
    },
    {
      key: 'Email',
      label: '会社メール',
      required: false,
      type: 'email',
      aliases: ['メール', 'メールアドレス', 'email', '会社メール', 'mail'],
    },
    {
      key: 'Department',
      label: '部署',
      required: false,
      type: 'string',
      aliases: ['部署', '所属', '部門', '事業部', 'department', 'division'],
    },
    {
      key: 'Title',
      label: '役職',
      required: false,
      type: 'string',
      aliases: ['役職', '肩書', '職位', 'title', 'position'],
    },
    {
      key: 'EmploymentType',
      label: '雇用形態',
      required: false,
      type: 'string',
      aliases: [
        '雇用形態',
        '区分',
        '社員区分',
        'employment',
        'employment type',
      ],
      options: ['fulltime', 'contract', 'parttime', 'outsourcing'],
      optionLabels: {
        fulltime: '正社員',
        contract: '契約社員',
        parttime: 'アルバイト・パート',
        outsourcing: '業務委託',
      },
    },
    {
      key: 'JoinedAt',
      label: '入社日',
      required: false,
      type: 'date',
      aliases: ['入社日', '入社', '雇入日', 'joined', 'hire date', '開始日'],
    },
    {
      key: 'LeftAt',
      label: '退社日',
      required: false,
      type: 'date',
      aliases: ['退社日', '退職日', '契約終了日', 'left', 'end date', '終了日'],
    },
  ],
};

/** 勤怠・工数データ */
const TIMESHEET: TargetSchema = {
  id: 'timesheet',
  name: '勤怠・工数',
  origin: 'preset',
  category: 'hr',
  fields: [
    {
      key: 'Date',
      label: '日付',
      required: true,
      type: 'date',
      aliases: ['日付', '日', '作業日', '勤務日', 'date', 'day'],
    },
    {
      key: 'EmployeeName',
      label: '担当者',
      required: true,
      type: 'string',
      aliases: ['担当者', '氏名', '名前', '社員', 'employee', 'name', 'member'],
    },
    {
      key: 'ProjectName',
      label: 'プロジェクト',
      required: false,
      type: 'string',
      aliases: ['プロジェクト', '案件', '業務', 'project', 'task', '作業内容'],
    },
    {
      key: 'Hours',
      label: '工数(時間)',
      required: false,
      type: 'number',
      aliases: ['工数', '時間', '作業時間', '稼働時間', 'hours', 'time'],
    },
    {
      key: 'StartTime',
      label: '開始時刻',
      required: false,
      type: 'string',
      aliases: ['開始', '開始時刻', '出社', '始業', 'start', 'start time'],
    },
    {
      key: 'EndTime',
      label: '終了時刻',
      required: false,
      type: 'string',
      aliases: ['終了', '終了時刻', '退社', '終業', 'end', 'end time'],
    },
    {
      key: 'Note',
      label: '備考',
      required: false,
      type: 'string',
      aliases: ['備考', 'メモ', 'コメント', 'note', 'remarks'],
    },
  ],
};

export const PRESET_SCHEMAS: TargetSchema[] = [
  // CRM
  SALESFORCE_LEAD,
  HUBSPOT_CONTACT,
  DYNAMICS_LEAD,
  DYNAMICS_CONTACT,
  DYNAMICS_ACCOUNT,
  // MA・メール配信
  MA_CONTACT_LIST,
  MARKETO_LEAD,
  NEWSLETTER_LIST,
  // 名刺・人脈
  BUSINESS_CARD,
  // 採用
  APPLICANT_LIST,
  // 会計・経費
  INVOICE_LINE,
  EXPENSE_REPORT,
  // 配送・EC
  SHIPPING_LABEL,
  EC_ORDER,
  PRODUCT_MASTER,
  // 広告レポート
  AD_REPORT,
  // 人事・勤怠
  EMPLOYEE_ROSTER,
  TIMESHEET,
];

export function getPresetById(id: string): TargetSchema | undefined {
  return PRESET_SCHEMAS.find((s) => s.id === id);
}

/**
 * ユーザーがアップロードした「インポート用シート」のヘッダー行から
 * ターゲットスキーマを生成する。各列名をそのままキー兼ラベルにする。
 */
export function schemaFromUploadedHeader(dataset: SourceDataset): TargetSchema {
  const fields: TargetField[] = dataset.columns.map((c) => ({
    key: c.name,
    label: c.name,
    required: false,
    type: c.inferredType === 'empty' ? 'string' : c.inferredType,
    aliases: [c.name],
  }));
  return {
    id: `uploaded-${Date.now()}`,
    name: `アップロード: ${dataset.fileName}`,
    origin: 'uploaded',
    fields,
  };
}
